services:
  libretv:
    # image: bestzwei/libretv:latest  # 注释掉远程镜像
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libretv
    ports:
      - "8899:8080" # 将内部 8080 端口映射到主机的 8899 端口
    # 如需访问控制，可在此处添加 PASSWORD 等环境变量
    environment: {}
#    volumes:
#      - libretv_data:/app # 不要修改
    restart: unless-stopped

#volumes:
#  libretv_data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ${PWD:-.}/data # 可将 ${PWD:-.} 修改为你想要的路径，默认为当前目录下的 data 文件夹
